### ISSUE TITLE
Update OPAM package?

### ISSUE THREAD

**Issue by nv-vn** [j0sh/ocaml-gensqlite#5]
Hi j0sh,
First of all, awesome work on gensqlite! It's been super convenient to use for my projects thus far. Anyways, the package available on OPAM corresponds to the initial commit for this repo (August 12, 2015). However, there were some changes made since then that aren't officially released to OPAM. I'm not sure if they're considered incomplete (in which case I could help out keeping them up-to-date), but would you be willing to update the release on OPAM?
Thanks, nv

**Comment by j0sh** [comment]
I completely missed this issue, sorry about that. The changes modify the syntax significantly following [sqlexpr](https://github.com/mfp/ocaml-sqlexpr/issues) -- and now that sqlexpr has PPX support, I'm not sure there is much of a place for this library anymore. If you're going to have to update the syntax for a new OPAM version anyway, then maybe sqlexpr would work better for you?

**Comment by nv-vn** [comment]
Thanks for the pointer, I'll just switch to sqlexpr where relevant!
